import type { Product } from './products'

// Firestore가 비어있거나 실패할 때 사용하는 정적 폴백 데이터
// 이미지: public/products/*.png (Vercel 정적 파일)
export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 'static-1',
    name: '아보리덤 치약',
    tagline: '편백 심재 추출물로 지키는 구강 건강',
    desc: '편백나무 심재 추출물의 천연 항균력으로 구강 세균을 억제합니다. 불소·합성향료 무첨가, 온 가족이 안심하고 사용할 수 있는 자연주의 치약입니다.',
    category: '구강/바디케어',
    image: '/products/toothpaste.png',
    badge: null,
    storeUrl: 'https://smartstore.naver.com/schinoki/products/4547743127',
    visible: true,
    order: 1,
  },
  {
    id: 'static-2',
    name: '심재편백수',
    tagline: '편백 속살에서 끌어낸 순수한 물',
    desc: '1979년부터 직접 키운 편백나무 심재에서만 추출한 고순도 편백수입니다. 일반 편백잎보다 피톤치드 함량이 높아 피부 진정·보습 효과가 탁월합니다.',
    category: '편백수/오일',
    image: '/products/hinoki-water.png',
    badge: 'Best',
    storeUrl: 'https://smartstore.naver.com/schinoki/products/2321580539',
    visible: true,
    order: 2,
  },
  {
    id: 'static-3',
    name: '아보리덤 바디워시',
    tagline: '온몸으로 마시는 편백 목욕',
    desc: '샤워 때마다 편백림을 걷는 듯한 피톤치드 향을 경험하세요. 심재편백수가 함유되어 세정 후에도 피부가 촉촉하고 차분하게 가라앉습니다.',
    category: '구강/바디케어',
    image: '/products/body-wash.png',
    badge: null,
    storeUrl: 'https://smartstore.naver.com/schinoki/products/5367370677',
    visible: true,
    order: 3,
  },
  {
    id: 'static-4',
    name: '편백 방향제',
    tagline: '집 안을 편백림으로 채우다',
    desc: '편백 심재에서 증류 추출한 순수 피톤치드 원액을 담은 디퓨저입니다. 합성향료 없이 자연 그대로의 편백 향이 실내 공기를 정화하고 마음을 편안하게 합니다.',
    category: '생활용품',
    image: '/products/diffuser.png',
    badge: null,
    storeUrl: 'https://smartstore.naver.com/schinoki/products/13135527849',
    visible: true,
    order: 4,
  },
  {
    id: 'static-5',
    name: '아보리덤 편백그대로 샴푸',
    tagline: '두피부터 시작하는 자연 치유',
    desc: '편백 심재오일과 천연 계면활성제가 두피의 과잉 피지와 노폐물을 깔끔하게 제거합니다. 사용 후 두피가 시원하고 모발에 자연스러운 윤기가 납니다.',
    category: '구강/바디케어',
    image: '/products/shampoo.png',
    badge: '인기 1위',
    storeUrl: 'https://smartstore.naver.com/schinoki/products/5192274059',
    visible: true,
    order: 5,
  },
  {
    id: 'static-6',
    name: '아보리덤 편백 마스크팩',
    tagline: '숲에서 온 피부 진정 마스크',
    desc: '심재편백수를 듬뿍 담은 시트 마스크입니다. 민감하고 달아오른 피부를 빠르게 진정시키고, 편백 피톤치드가 피부 결을 촉촉하게 정돈합니다.',
    category: '편백수/오일',
    image: '/products/mask-pack.png',
    badge: 'New',
    storeUrl: 'https://smartstore.naver.com/schinoki/products/12728042455',
    visible: true,
    order: 6,
  },
  {
    id: 'static-7',
    name: '아보리덤 편백 하트우드 오일',
    tagline: '특허받은 심재 추출 기술의 정수',
    desc: '국내 유일 편백 심재(Heartwood)오일 특허 기술로 생산합니다. 심재 특유의 진한 피톤치드 향과 함께 피부 장벽 강화, 항균·항염 효과를 제공합니다.',
    category: '편백수/오일',
    image: '/products/heartwood-oil.png',
    badge: '특허',
    storeUrl: 'https://smartstore.naver.com/schinoki/products/12600870706',
    visible: true,
    order: 7,
  },
  {
    id: 'static-8',
    name: '편백 바디케어 선물세트',
    tagline: '자연을 선물하세요',
    desc: '아보리덤 바디케어 제품을 엄선하여 구성한 프리미엄 선물세트입니다. 소중한 분께 편백 자연 치유의 가치를 정성껏 전달하세요.',
    category: '생활용품',
    image: '/products/gift-set.png',
    badge: null,
    storeUrl: 'https://smartstore.naver.com/schinoki/products/12585328348',
    visible: true,
    order: 8,
  },
  {
    id: 'static-9',
    name: '심재팩 방향제',
    tagline: '작은 주머니에 담은 편백림',
    desc: '편백 심재 추출 후 남은 순수 목재 부스러기를 활용한 천연 방향 파우치입니다. 옷장·서랍·자동차 어디든 은은한 편백 향과 탈취 효과를 선사합니다.',
    category: '생활용품',
    image: '/products/sachet-diffuser.png',
    badge: null,
    storeUrl: 'https://smartstore.naver.com/schinoki/products/11819720566',
    visible: true,
    order: 9,
  },
  {
    id: 'static-10',
    name: '심재 편백수 스프레이',
    tagline: '언제 어디서나 숲 속 청량함을',
    desc: '심재편백수를 고압 미세분무로 담은 즉각 진정 스프레이입니다. 화장 위에 덧뿌려도 촉촉하게 밀착되며, 실내 공기 정화에도 활용할 수 있습니다.',
    category: '편백수/오일',
    image: '/products/water-spray.png',
    badge: null,
    storeUrl: 'https://smartstore.naver.com/schinoki/products/11697357584',
    visible: true,
    order: 10,
  },
  {
    id: 'static-11',
    name: '강아지 펫 샴푸',
    tagline: '반려견도 편백으로 건강하게',
    desc: '편백 심재 추출물의 천연 항균·탈취력으로 반려견 피부를 청결하게 관리합니다. 합성향료·파라벤 무첨가로 민감한 반려견 피부에도 안심하고 사용할 수 있습니다.',
    category: '생활용품',
    image: '/products/pet-shampoo.png',
    badge: null,
    storeUrl: 'https://smartstore.naver.com/schinoki/products/6911282927',
    visible: true,
    order: 11,
  },
]
